### PR TITLE
parser rewrite

### PR DESCRIPTION
**Pull request by rp-**
Hi!

I know this project didn't see any work in 2 years, but I needed a vedirect->prometheus solution.
And took this as a starting point, but for me the parser usage was very cumbersome
(having to handle parsing buffers on the user side,...)
So I basically rewrote the whole thing and it now supports also MPPT blocks and is easier to use(from a user point).
Also the new parser tries to ignore data errors and just keep parsing, as data is sent every second anyway.

It still doesn't support the HEX protocol, but it now ignores hex messages that are sent(on my MPPT) from time to time.

### CODE REVIEW

**Comment by rp-** [comment]
@chevdor maybe also interesting for you

**Comment by chevdor** [comment]
I did not forget my PR but it has been sitting idel for a while. I have on my todo to reopen the topic... but no clue when I will manage. Thanks for the ping !

**Comment by dbr** [comment]
This is great, thanks! The old parser was indeed pretty clunky to use, this looks much nicer

I'll try and do a few minor bits of tidy up and release this as 0.2 soon, hopefully sometime this weekend

Looks like it should, in theory at least, merge quite nicely with @chevdor's PR as that didn't touch the parser. I think having the parser just ignore errors and carry on makes sense, as you say the device resends the data every second (would be different for the hex API, but I'd suspect the library would need to be significantly rewritten for that anyway)

Your [vedirect-prom](https://github.com/rp-/vedirect-prom) looks useful - I originally used this library to write to InfluxDB, but since switched things to Prometheus and never got around to resurrecting it

**Comment by dbr** [comment]
This is now released as [v0.2.0](https://crates.io/crates/vedirect/0.2.0) - thanks again!

**Pull request merged**
